export const ALL_TRANSACTION_REQUEST = "ALL_TRANSACTION_REQUEST";
export const ALL_TRANSACTION_SUCCESS = "ALL_TRANSACTION_SUCCESS";
export const ALL_TRANSACTION_FAIL = "ALL_TRANSACTION_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";