export const ALL_CUSTOMER_REQUEST = "ALL_CUSTOMER_REQUEST";
export const ALL_CUSTOMER_SUCCESS = "ALL_CUSTOMER_SUCCESS";
export const ALL_CUSTOMER_FAIL = "ALL_CUSTOMER_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";